# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(max_length=100, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gendar',
            field=models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('another', 'その他')], max_length=100, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('01', '自営者'), ('02', '会社・団体役員'), ('03', '管理職'), ('04', '一般事務職'), ('05', '専門職'), ('06', '教職・研究職'), ('07', '技能・作業職'), ('08', '販売職'), ('09', '無職'), ('10', 'その他')], max_length=100, verbose_name='職種'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prefecture',
            field=models.CharField(blank=True, choices=[('01', '北海道'), ('02', '青森'), ('03', '岩手'), ('04', '宮城'), ('05', '秋田'), ('06', '山形'), ('07', '福島'), ('08', '茨城'), ('09', '栃木'), ('10', '群馬'), ('11', '埼玉'), ('12', '千葉'), ('13', '東京'), ('14', '神奈川'), ('15', '新潟'), ('16', '富山'), ('17', '石川'), ('18', '福井'), ('19', '山梨'), ('20', '長野'), ('21', '岐阜'), ('22', '静岡'), ('23', '愛知'), ('24', '三重'), ('25', '滋賀'), ('26', '京都'), ('27', '大阪'), ('28', '兵庫'), ('29', '奈良'), ('30', '和歌山'), ('31', '鳥取'), ('32', '島根'), ('33', '岡山'), ('34', '広島'), ('35', '山口'), ('36', '徳島'), ('37', '香川'), ('38', '愛媛'), ('39', '高知'), ('40', '福岡'), ('41', '佐賀'), ('42', '長崎'), ('43', '熊本'), ('44', '大分'), ('45', '宮崎'), ('46', '鹿児島'), ('47', '沖縄')], max_length=100),
        ),
    ]
