# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20171224_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='private_scene',
        ),
        migrations.DeleteModel(
            name='PrivateScene',
        ),
    ]
