# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20171224_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateScene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_scene', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='img',
            name='private_scene',
            field=models.ManyToManyField(blank=True, to='upload.PrivateScene'),
        ),
    ]
