# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_img_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='category',
            field=models.CharField(blank=True, choices=[('event01', '後期中間発表')], max_length=255),
        ),
        migrations.AlterField(
            model_name='img',
            name='file',
            field=models.ImageField(upload_to=upload.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='img',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
