# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20171129_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='category',
            field=models.CharField(blank=True, choices=[('後期中間発表で着る服', '後期中間発表で着る服')], max_length=255, verbose_name='お題'),
        ),
        migrations.AlterField(
            model_name='img',
            name='file',
            field=models.ImageField(upload_to=upload.models.get_image_path, verbose_name='ファイル'),
        ),
        migrations.AlterField(
            model_name='img',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='未登録ユーザに公開'),
        ),
        migrations.AlterField(
            model_name='img',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='タイトル'),
        ),
    ]
