# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 04:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('upload', '0005_favoriteimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='favoriteimg',
            name='image',
        ),
        migrations.RemoveField(
            model_name='favoriteimg',
            name='user',
        ),
        migrations.AddField(
            model_name='img',
            name='favorited',
            field=models.IntegerField(default=0, verbose_name='お気に入り登録数'),
        ),
        migrations.DeleteModel(
            name='FavoriteImg',
        ),
    ]
