# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20180119_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='rate_ave',
        ),
        migrations.RemoveField(
            model_name='img',
            name='rate_sum',
        ),
    ]
