# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_auto_20171205_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='item1_1',
            field=models.CharField(blank=True, choices=[('item1-1', 'item1-1'), ('item1-2', 'item1-2'), ('item1-3', 'item1-3'), ('item1-4', 'item1-4'), ('item1-5', 'item1-5'), ('item1-6', 'item1-6'), ('item1-7', 'item1-7'), ('item1-8', 'item1-8'), ('item1-9', 'item1-9'), ('item1-10', 'item1-10')], max_length=255, verbose_name='上半身1'),
        ),
        migrations.AlterField(
            model_name='img',
            name='item1_2',
            field=models.CharField(blank=True, choices=[('item1-1', 'item1-1'), ('item1-2', 'item1-2'), ('item1-3', 'item1-3'), ('item1-4', 'item1-4'), ('item1-5', 'item1-5'), ('item1-6', 'item1-6'), ('item1-7', 'item1-7'), ('item1-8', 'item1-8'), ('item1-9', 'item1-9'), ('item1-10', 'item1-10')], max_length=255, verbose_name='上半身2'),
        ),
        migrations.AlterField(
            model_name='img',
            name='item1_3',
            field=models.CharField(blank=True, choices=[('item1-1', 'item1-1'), ('item1-2', 'item1-2'), ('item1-3', 'item1-3'), ('item1-4', 'item1-4'), ('item1-5', 'item1-5'), ('item1-6', 'item1-6'), ('item1-7', 'item1-7'), ('item1-8', 'item1-8'), ('item1-9', 'item1-9'), ('item1-10', 'item1-10')], max_length=255, verbose_name='上半身3'),
        ),
        migrations.AlterField(
            model_name='img',
            name='item1_4',
            field=models.CharField(blank=True, choices=[('item1-1', 'item1-1'), ('item1-2', 'item1-2'), ('item1-3', 'item1-3'), ('item1-4', 'item1-4'), ('item1-5', 'item1-5'), ('item1-6', 'item1-6'), ('item1-7', 'item1-7'), ('item1-8', 'item1-8'), ('item1-9', 'item1-9'), ('item1-10', 'item1-10')], max_length=255, verbose_name='上半身4'),
        ),
        migrations.AlterField(
            model_name='img',
            name='item2_1',
            field=models.CharField(blank=True, choices=[('item2-1', 'item2-1'), ('item2-2', 'item2-2'), ('item2-3', 'item2-3'), ('item2-4', 'item2-4'), ('item2-5', 'item2-5'), ('item2-6', 'item2-6'), ('item2-7', 'item2-7'), ('item2-8', 'item2-8'), ('item2-9', 'item2-9'), ('item2-10', 'item2-10')], max_length=255, verbose_name='下半身1'),
        ),
        migrations.AlterField(
            model_name='img',
            name='item2_2',
            field=models.CharField(blank=True, choices=[('item2-1', 'item2-1'), ('item2-2', 'item2-2'), ('item2-3', 'item2-3'), ('item2-4', 'item2-4'), ('item2-5', 'item2-5'), ('item2-6', 'item2-6'), ('item2-7', 'item2-7'), ('item2-8', 'item2-8'), ('item2-9', 'item2-9'), ('item2-10', 'item2-10')], max_length=255, verbose_name='下半身2'),
        ),
        migrations.AlterField(
            model_name='img',
            name='item2_3',
            field=models.CharField(blank=True, choices=[('item2-1', 'item2-1'), ('item2-2', 'item2-2'), ('item2-3', 'item2-3'), ('item2-4', 'item2-4'), ('item2-5', 'item2-5'), ('item2-6', 'item2-6'), ('item2-7', 'item2-7'), ('item2-8', 'item2-8'), ('item2-9', 'item2-9'), ('item2-10', 'item2-10')], max_length=255, verbose_name='下半身3'),
        ),
    ]
