# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_auto_20171205_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('item2-1', 'アイテム2-1'), ('item2-2', 'アイテム2-2'), ('item2-3', 'アイテム2-3'), ('item2-4', 'アイテム2-4'), ('item2-5', 'アイテム2-5'), ('item2-6', 'アイテム2-6'), ('item2-7', 'アイテム2-7'), ('item2-8', 'アイテム2-8'), ('item2-9', 'アイテム2-9'), ('item2-10', 'アイテム2-10')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoordinateStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('item1-1', 'アイテム1-1'), ('item1-2', 'アイテム1-2'), ('item1-3', 'アイテム1-3'), ('item1-4', 'アイテム1-4'), ('item1-5', 'アイテム1-5'), ('item1-6', 'アイテム1-6'), ('item1-7', 'アイテム1-7'), ('item1-8', 'アイテム1-8'), ('item1-9', 'アイテム1-9'), ('item1-10', 'アイテム1-10')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('item1-1', 'アイテム1-1'), ('item1-2', 'アイテム1-2'), ('item1-3', 'アイテム1-3'), ('item1-4', 'アイテム1-4'), ('item1-5', 'アイテム1-5'), ('item1-6', 'アイテム1-6'), ('item1-7', 'アイテム1-7'), ('item1-8', 'アイテム1-8'), ('item1-9', 'アイテム1-9'), ('item1-10', 'アイテム1-10')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('item2-1', 'アイテム2-1'), ('item2-2', 'アイテム2-2'), ('item2-3', 'アイテム2-3'), ('item2-4', 'アイテム2-4'), ('item2-5', 'アイテム2-5'), ('item2-6', 'アイテム2-6'), ('item2-7', 'アイテム2-7'), ('item2-8', 'アイテム2-8'), ('item2-9', 'アイテム2-9'), ('item2-10', 'アイテム2-10')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(choices=[('item1-1', 'アイテム1-1'), ('item1-2', 'アイテム1-2'), ('item1-3', 'アイテム1-3'), ('item1-4', 'アイテム1-4'), ('item1-5', 'アイテム1-5'), ('item1-6', 'アイテム1-6'), ('item1-7', 'アイテム1-7'), ('item1-8', 'アイテム1-8'), ('item1-9', 'アイテム1-9'), ('item1-10', 'アイテム1-10')], max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='img',
            name='item1_1',
        ),
        migrations.RemoveField(
            model_name='img',
            name='item1_2',
        ),
        migrations.RemoveField(
            model_name='img',
            name='item1_3',
        ),
        migrations.RemoveField(
            model_name='img',
            name='item1_4',
        ),
        migrations.RemoveField(
            model_name='img',
            name='item2_1',
        ),
        migrations.RemoveField(
            model_name='img',
            name='item2_2',
        ),
        migrations.RemoveField(
            model_name='img',
            name='item2_3',
        ),
        migrations.AddField(
            model_name='img',
            name='color',
            field=models.ManyToManyField(to='upload.ClothColor', verbose_name='色'),
        ),
        migrations.AddField(
            model_name='img',
            name='purpose',
            field=models.ManyToManyField(to='upload.Purpose', verbose_name='意図'),
        ),
        migrations.AddField(
            model_name='img',
            name='season',
            field=models.ManyToManyField(to='upload.Season', verbose_name='季節'),
        ),
        migrations.AddField(
            model_name='img',
            name='situation',
            field=models.ManyToManyField(to='upload.Situation', verbose_name='状況'),
        ),
        migrations.AddField(
            model_name='img',
            name='style',
            field=models.ManyToManyField(to='upload.CoordinateStyle', verbose_name='スタイル'),
        ),
    ]
