# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_auto_20171205_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothcolor',
            name='color',
            field=models.CharField(choices=[('item1-1', 'アイテム1-1'), ('item1-2', 'アイテム1-2'), ('item1-3', 'アイテム1-3'), ('item1-4', 'アイテム1-4'), ('item1-5', 'アイテム1-5'), ('item1-6', 'アイテム1-6'), ('item1-7', 'アイテム1-7'), ('item1-8', 'アイテム1-8'), ('item1-9', 'アイテム1-9'), ('item1-10', 'アイテム1-10')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='img',
            name='color',
            field=models.ManyToManyField(to='upload.ClothColor', verbose_name='色'),
        ),
        migrations.AlterField(
            model_name='img',
            name='purpose',
            field=models.ManyToManyField(to='upload.Purpose', verbose_name='意図'),
        ),
        migrations.AlterField(
            model_name='img',
            name='season',
            field=models.ManyToManyField(to='upload.Season', verbose_name='季節'),
        ),
        migrations.AlterField(
            model_name='img',
            name='situation',
            field=models.ManyToManyField(to='upload.Situation', verbose_name='状況'),
        ),
        migrations.AlterField(
            model_name='img',
            name='style',
            field=models.ManyToManyField(to='upload.CoordinateStyle', verbose_name='スタイル'),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('item1-1', 'アイテム1-1'), ('item1-2', 'アイテム1-2'), ('item1-3', 'アイテム1-3'), ('item1-4', 'アイテム1-4'), ('item1-5', 'アイテム1-5'), ('item1-6', 'アイテム1-6'), ('item1-7', 'アイテム1-7'), ('item1-8', 'アイテム1-8'), ('item1-9', 'アイテム1-9'), ('item1-10', 'アイテム1-10')], max_length=255, unique=True),
        ),
    ]
