# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_auto_20171205_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothcolor',
            name='color',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='coordinatestyle',
            name='style',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='purpose',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='situation',
            name='situation',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
