# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0016_auto_20171215_1653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClothColor',
            new_name='Color',
        ),
        migrations.RenameModel(
            old_name='CoordinateStyle',
            new_name='Member',
        ),
        migrations.RenameModel(
            old_name='Purpose',
            new_name='Place',
        ),
        migrations.RenameField(
            model_name='img',
            old_name='style',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='img',
            old_name='purpose',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='style',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='purpose',
            new_name='place',
        ),
    ]
